# Generated by Django 3.1.1 on 2020-09-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200915_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinternships',
            name='description_file',
            field=models.FileField(upload_to='attachments/% Y/% m/'),
        ),
    ]
