# Generated by Django 3.1.1 on 2020-09-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200915_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinternships',
            name='description_file',
            field=models.FileField(upload_to='attachments/%Y/%m/'),
        ),
    ]
