# Generated by Django 3.1.1 on 2020-09-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200915_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupinternships',
            name='description_file',
            field=models.FileField(upload_to='media/attachments/%Y/%m/'),
        ),
    ]
