# Generated by Django 3.1.1 on 2020-09-15 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200915_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupinternships',
            name='last_date_to_apply',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
